appname: "MyApp"
charset: "UTF-8"
version: "0.0.1"

# we specify a layout even if our layout doesn't contain a content var
# we are doing single page app, so we only send the layout and angular will take care
# of changing views
#layout: "main"

# template engine
# use TT, it's just better
template: template_toolkit
engines:
  template_toolkit:
    start_tag: '[%'
    stop_tag: '%]'

serializer: "JSON"

# we run our dancer app using starman. we use a http server as a proxy so we left 
# this below to use

#plack_middlewares:
#  -
#    - ReverseProxy

