# configuration file for production environment

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

# although the following section seems the same in each environments, we don't put in into 
# the main config.yml. this will let us use different databases for each environments

# session storage using DBI (compatible with MySQL and SQLite only)
session: "DBI"
session_options:
  dsn:      "DBI:mysql:database=myapp;host=127.0.0.1;port=3306"
  table:    "sessions"
  user:     "myappuser"
  password: "myapppassword"
  
# we have included plugin configuration templates for 3 modules we use a lot:
# DP::Database, DP::Auth::Extensible and DP::DBIC
# we've only uncommented the Database plugin config since you will probably need this
plugins:
  Database:
    driver: 'mysql'
    database: 'myapp'
    host: 'localhost'
    port: 3306
    username: 'myappuser'
    password: 'myapppassword'
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
    log_queries: 0
#  Auth::Extensible:
#    realms:
#      users:
#        provider: Database
#        users_table: 'users'
#        roles_table: 'roles'
#        users_roles_table: 'user_roles'
#    no_default_pages: 1
#    no_login_handler: 1
#    no_api_change_warning: 1
#  DBIC:
#    default:
#      dsn: 'dbi:mysql:myapp'
#      schema_class: 'MyApp::Schema'
#      user: 'myappuser'
#      pass: 'myapppassword'
#      options:
#        RaiseError: 1
#        PrintError: 1
